name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Debug - List build output
        run: |
          echo "Contents of out directory:"
          ls -la out/
          echo "\nContents of out/_next directory:"
          ls -la out/_next/
          echo "\nContents of out/_next/static directory:"
          ls -la out/_next/static/
          echo "\nContents of out/_next/static/css directory:"
          ls -la out/_next/static/css/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }} 